### ISSUE TITLE
Issue with tty-tables

### ISSUE THREAD

**Issue by maxeonyx** [druc/todo-cli#3]
Hi, I just installed this tool, got an error in the tty-tables package, after creating my first todo and then typing: `todo`

```
/usr/lib/node_modules/todo-cli/node_modules/tty-table/src/main.js:290
            prop = prop.toFixed(2)-0.01;
                        ^

TypeError: prop.toFixed is not a function
    at Object._private.getColumnWidths (/usr/lib/node_modules/todo-cli/node_modules/tty-table/src/main.js:290:16)
    at Object._private.setup (/usr/lib/node_modules/todo-cli/node_modules/tty-table/src/main.js:323:42)
    at module.exports (/usr/lib/node_modules/todo-cli/node_modules/tty-table/src/main.js:460:20)
    at display (/usr/lib/node_modules/todo-cli/bin/todo:41:17)
    at /usr/lib/node_modules/todo-cli/bin/todo:126:9
    at TODO.filter (/usr/lib/node_modules/todo-cli/lib/index.js:168:5)
    at Object.opened (/usr/lib/node_modules/todo-cli/bin/todo:73:18)
    at /usr/lib/node_modules/todo-cli/bin/todo:117:30
    at /usr/lib/node_modules/todo-cli/lib/index.js:20:13
    at /usr/lib/node_modules/todo-cli/lib/index.js:47:9
```

I went into my global node_modules/todo-cli folder and forced an upgrade of the tty-tables package to the latest version (2.1.0). This fixed the issue (but I can't say whether there are any other problems yet)

my node version is v6.5.0

Thanks

**Comment by druc** [comment]
Hi @Maxeonyx! Thank's for reporting this issue. The problem occurs when the window is too small for the tty-table to do its thing. 

As you said, updating the dependencies does the job. Did that in v1.1.3

Thanks again for reporting this!
